# Generated by Django 6.0.3 on 2026-03-22 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Receita",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="Utilizador",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="Ingrediente",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=100)),
                (
                    "receita",
                    models.ManyToManyField(
                        blank=True,
                        null=True,
                        related_name="ingredientes",
                        to="receita.receita",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="receita",
            name="utilizador",
            field=models.ManyToManyField(
                blank=True,
                null=True,
                related_name="receitas_favoritas",
                to="receita.utilizador",
            ),
        ),
    ]
