# Generated by Django 6.0.3 on 2026-03-22 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("receita", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="ingrediente",
            name="receita",
            field=models.ManyToManyField(
                blank=True, null=True, related_name="ingredientes", to="receita.receita"
            ),
        ),
        migrations.AddField(
            model_name="receita",
            name="utilizador",
            field=models.ManyToManyField(
                blank=True,
                null=True,
                related_name="receitas_favoritas",
                to="receita.utilizador",
            ),
        ),
    ]
