# Generated by Django 6.0.3 on 2026-03-22 16:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ginásio", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="pts",
            name="ginasio",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="pts",
                to="ginásio.ginásio",
            ),
        ),
        migrations.AddField(
            model_name="sessão",
            name="membro",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="sessões",
                to="ginásio.membro",
            ),
        ),
        migrations.AddField(
            model_name="sessão",
            name="pt",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="sessões",
                to="ginásio.pts",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="sessão",
            unique_together={("pt", "data", "hora")},
        ),
    ]
