# Generated by Django 6.0.4 on 2026-04-15 09:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("Escola", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="aluno",
            options={"verbose_name": "Aluno", "verbose_name_plural": "Alunos"},
        ),
        migrations.AlterModelOptions(
            name="curso",
            options={"verbose_name": "Curso", "verbose_name_plural": "Cursos"},
        ),
        migrations.AlterModelOptions(
            name="professor",
            options={"verbose_name": "Professor", "verbose_name_plural": "Professores"},
        ),
    ]
