# Generated by Django 6.0.3 on 2026-03-22 02:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("escola", "0001_initial"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="alunos",
            new_name="Aluno",
        ),
        migrations.RenameModel(
            old_name="professores",
            new_name="Professor",
        ),
    ]
