# Generated by Django 6.0.3 on 2026-03-22 16:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("escola", "0002_rename_alunos_aluno_rename_professores_professor"),
    ]

    operations = [
        migrations.AddField(
            model_name="aluno",
            name="turma",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="alunos",
                to="escola.turma",
            ),
        ),
        migrations.AddField(
            model_name="professor",
            name="escola",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="professores",
                to="escola.escola",
            ),
        ),
        migrations.AddField(
            model_name="turma",
            name="escola",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="turmas",
                to="escola.escola",
            ),
        ),
        migrations.AddField(
            model_name="turma",
            name="professor",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="turma",
                to="escola.professor",
            ),
        ),
    ]
