# Generated by Django 6.0.5 on 2026-06-22 17:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Faccao",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=100)),
                ("lado", models.CharField(max_length=100)),
                ("descricao", models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name="Planeta",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=100)),
                ("clima", models.CharField(max_length=100)),
                ("setor", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="Personagem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=100)),
                ("idade", models.IntegerField()),
                ("especie", models.CharField(max_length=300)),
                ("primeira_apariçao", models.TextField()),
                (
                    "faccao",
                    models.ManyToManyField(
                        blank=True, related_name="personagens", to="holocron.faccao"
                    ),
                ),
                (
                    "planeta_origem",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="personagens",
                        to="holocron.planeta",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Missao",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("titulo", models.CharField(max_length=100)),
                ("dificuldade", models.CharField(max_length=300)),
                ("objetivo", models.TextField()),
                (
                    "participantes",
                    models.ManyToManyField(
                        blank=True, related_name="missoes", to="holocron.personagem"
                    ),
                ),
                (
                    "planeta_destino",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="missoes",
                        to="holocron.planeta",
                    ),
                ),
            ],
        ),
    ]
