# Generated by Django 6.0.4 on 2026-04-11 09:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Competencia",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name="Docente",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=200)),
                ("email", models.EmailField(max_length=254)),
                ("pagina_pessoal_url", models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name="Formacao",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=200)),
                ("instituicao", models.CharField(max_length=200)),
                ("descricao", models.TextField()),
                ("data_inicio", models.DateField()),
                ("data_fim", models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name="Licenciatura",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=100)),
                ("descrição", models.TextField()),
                ("duracao", models.CharField(max_length=100)),
                ("url_pagina_oficial", models.URLField()),
                ("requisitos", models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name="MakingOf",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("titulo", models.CharField(max_length=200)),
                ("descricao", models.TextField()),
                ("imagem_url", models.URLField(blank=True, null=True)),
                ("observacao", models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="Tecnologia",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=100)),
                ("url_oficial", models.URLField()),
                ("descricao", models.TextField()),
                ("logo_url", models.URLField()),
                ("nivel_interesse", models.IntegerField()),
                ("nivel_proficiencia", models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name="Unidade_Curricular",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=200)),
                ("ano_curricular", models.IntegerField()),
                ("semestre", models.IntegerField()),
                ("url_uc", models.URLField()),
                ("imagem_url", models.URLField()),
                (
                    "docente",
                    models.ManyToManyField(related_name="UCs", to="portfolio.docente"),
                ),
                (
                    "licenciatura",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="UCs",
                        to="portfolio.licenciatura",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Projeto",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=200)),
                ("descricao", models.TextField()),
                ("imagem_url", models.URLField()),
                ("link_projeto", models.URLField()),
                ("ano_curricular", models.IntegerField()),
                (
                    "competencia",
                    models.ManyToManyField(
                        related_name="projetos", to="portfolio.competencia"
                    ),
                ),
                (
                    "tecnologia",
                    models.ManyToManyField(
                        related_name="projetos", to="portfolio.tecnologia"
                    ),
                ),
                (
                    "uc",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="projetos",
                        to="portfolio.unidade_curricular",
                    ),
                ),
            ],
        ),
    ]
