# Generated by Django 6.0.5 on 2026-05-08 10:10

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Competencia",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=100)),
            ],
            options={
                "verbose_name": "Competência",
                "verbose_name_plural": "Competências",
            },
        ),
        migrations.CreateModel(
            name="Docente",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=100)),
                ("email", models.EmailField(max_length=254)),
                ("url_oficial", models.URLField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "Docente",
                "verbose_name_plural": "Docentes",
            },
        ),
        migrations.CreateModel(
            name="Formacao",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=100)),
                ("url_oficial", models.URLField(blank=True, null=True)),
                ("logo_oficial", models.ImageField(upload_to="media/")),
                ("descrição", models.CharField(max_length=100)),
                ("data_inicio", models.DateField()),
                ("data_fim", models.DateField()),
            ],
            options={
                "verbose_name": "Tecnologia",
                "verbose_name_plural": "Tecnologias",
            },
        ),
        migrations.CreateModel(
            name="Licenciatura",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=100)),
                ("descrição", models.CharField(max_length=100)),
                ("requisitos", models.CharField(max_length=100)),
                ("duração", models.CharField(max_length=100)),
                ("url_oficial", models.URLField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "Licenciatura",
                "verbose_name_plural": "Licenciaturas",
            },
        ),
        migrations.CreateModel(
            name="MakingOf",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("titulo", models.CharField(max_length=100)),
                (
                    "entidade",
                    models.CharField(
                        choices=[
                            ("licenciatura", "Licenciatura"),
                            ("unidade_curricular", "Unidade Curricular"),
                            ("docente", "Docente"),
                            ("projeto", "Projeto"),
                            ("tecnologia", "Tecnologia"),
                            ("competencia", "Competência"),
                            ("formacao", "Formação"),
                            ("tfc", "TFC"),
                        ],
                        default="nenhuma",
                        max_length=100,
                    ),
                ),
                ("descricao_trabalho", models.TextField()),
                ("decisoes_tomadas", models.TextField()),
                ("erros_encontrados", models.TextField(blank=True)),
                ("correcoes_realizadas", models.TextField(blank=True)),
                (
                    "imagem1",
                    models.ImageField(blank=True, null=True, upload_to="makingof/"),
                ),
                (
                    "imagem2",
                    models.ImageField(blank=True, null=True, upload_to="makingof/"),
                ),
            ],
            options={
                "verbose_name": "MakingOf",
                "verbose_name_plural": "MakingOf",
            },
        ),
        migrations.CreateModel(
            name="Projeto",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=100)),
                ("ano_curricular", models.IntegerField()),
                ("semestre", models.IntegerField()),
                ("imagem", models.ImageField(upload_to="media/")),
                ("conceitos_aplicados", models.CharField(max_length=100)),
            ],
            options={
                "verbose_name": "Projeto",
                "verbose_name_plural": "Projetos",
            },
        ),
        migrations.CreateModel(
            name="Tecnologia",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=100)),
                ("url_oficial", models.URLField(blank=True, null=True)),
                ("logo_oficial", models.ImageField(upload_to="media/")),
                ("descrição", models.CharField(max_length=100)),
                (
                    "nivel_interesse",
                    models.IntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(10),
                        ]
                    ),
                ),
            ],
            options={
                "verbose_name": "Tecnologia",
                "verbose_name_plural": "Tecnologias",
            },
        ),
        migrations.CreateModel(
            name="TFC",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("titulo", models.CharField(max_length=100)),
                ("autor", models.CharField(max_length=100)),
                ("url_oficial", models.URLField(blank=True, null=True)),
                ("descrição", models.TextField()),
                ("imagem", models.ImageField(upload_to="media/")),
            ],
            options={
                "verbose_name": "TFC",
                "verbose_name_plural": "TFCs",
            },
        ),
        migrations.CreateModel(
            name="Unidade_Curricular",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=100)),
                ("ano_curricular", models.IntegerField()),
                ("semestre", models.IntegerField()),
                ("url_oficial", models.URLField(blank=True, null=True)),
                ("imagem", models.ImageField(upload_to="media/")),
            ],
            options={
                "verbose_name": "Unicade Curricular",
                "verbose_name_plural": "Unidades Curriculares",
            },
        ),
    ]
