# Generated by Django 6.0.5 on 2026-05-08 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="formacao",
            options={"verbose_name": "Formacao", "verbose_name_plural": "Formações"},
        ),
        migrations.RenameField(
            model_name="licenciatura",
            old_name="duração",
            new_name="duracao",
        ),
        migrations.RenameField(
            model_name="tfc",
            old_name="descrição",
            new_name="descricao",
        ),
        migrations.RemoveField(
            model_name="tecnologia",
            name="descrição",
        ),
        migrations.AddField(
            model_name="projeto",
            name="descricao",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="tecnologia",
            name="descricao",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="formacao",
            name="descrição",
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name="licenciatura",
            name="descrição",
            field=models.TextField(),
        ),
    ]
