# Generated by Django 6.0.4 on 2026-04-11 12:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="licenciatura",
            old_name="descrição",
            new_name="descricao",
        ),
    ]
