# Generated by Django 6.0.5 on 2026-05-08 10:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio", "0002_alter_formacao_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="projeto",
            name="competencia",
            field=models.ManyToManyField(
                related_name="projetos", to="portfolio.competencia"
            ),
        ),
        migrations.AddField(
            model_name="projeto",
            name="tecnologia",
            field=models.ManyToManyField(
                related_name="projetos", to="portfolio.tecnologia"
            ),
        ),
        migrations.AddField(
            model_name="projeto",
            name="uc",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="projetos",
                to="portfolio.unidade_curricular",
            ),
        ),
        migrations.AddField(
            model_name="unidade_curricular",
            name="docente",
            field=models.ManyToManyField(related_name="UCs", to="portfolio.docente"),
        ),
        migrations.AddField(
            model_name="unidade_curricular",
            name="licenciatura",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="UCs",
                to="portfolio.licenciatura",
            ),
        ),
    ]
