# Generated by Django 6.0.4 on 2026-04-11 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio", "0002_rename_descrição_licenciatura_descricao"),
    ]

    operations = [
        migrations.CreateModel(
            name="TFC",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("titulo", models.CharField(max_length=100)),
                ("autor", models.CharField(max_length=100)),
                ("resumo", models.TextField()),
                ("imagem", models.URLField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "TFC",
                "verbose_name_plural": "TFCs",
            },
        ),
        migrations.AlterModelOptions(
            name="competencia",
            options={
                "verbose_name": "Competência",
                "verbose_name_plural": "Competências",
            },
        ),
        migrations.AlterModelOptions(
            name="docente",
            options={"verbose_name": "Docente", "verbose_name_plural": "Docentes"},
        ),
        migrations.AlterModelOptions(
            name="formacao",
            options={"verbose_name": "Formação", "verbose_name_plural": "Formações"},
        ),
        migrations.AlterModelOptions(
            name="licenciatura",
            options={
                "verbose_name": "Licenciatura",
                "verbose_name_plural": "Licenciaturas",
            },
        ),
        migrations.AlterModelOptions(
            name="makingof",
            options={"verbose_name": "Making Of", "verbose_name_plural": "Making Of"},
        ),
        migrations.AlterModelOptions(
            name="projeto",
            options={"verbose_name": "Projeto", "verbose_name_plural": "Projetos"},
        ),
        migrations.AlterModelOptions(
            name="tecnologia",
            options={
                "verbose_name": "Tecnologia",
                "verbose_name_plural": "Tecnologias",
            },
        ),
        migrations.AlterModelOptions(
            name="unidade_curricular",
            options={
                "verbose_name": "Unidade Curricular",
                "verbose_name_plural": "Unidades Curriculares",
            },
        ),
    ]
