# Generated by Django 6.0.5 on 2026-05-11 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "portfolio",
            "0003_projeto_competencia_projeto_tecnologia_projeto_uc_and_more",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="licenciatura",
            name="descrição",
        ),
        migrations.AddField(
            model_name="licenciatura",
            name="creditos",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="licenciatura",
            name="descricao",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="licenciatura",
            name="formato_curso",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="licenciatura",
            name="semestres",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="licenciatura",
            name="requisitos",
            field=models.JSONField(blank=True, null=True),
        ),
    ]
