# Generated by Django 6.0.4 on 2026-04-15 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "portfolio",
            "0003_tfc_alter_competencia_options_alter_docente_options_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="makingof",
            name="imagem_url",
            field=models.ImageField(
                blank=True, null=True, upload_to="portfolio/makingof"
            ),
        ),
    ]
