# Generated by Django 6.0.5 on 2026-05-11 15:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "portfolio",
            "0004_remove_licenciatura_descrição_licenciatura_creditos_and_more",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="tfc",
            name="url_oficial",
        ),
    ]
