# Generated by Django 6.0.5 on 2026-05-20 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio", "0005_remove_tfc_url_oficial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tfc",
            name="autor",
            field=models.CharField(max_length=300),
        ),
    ]
