# Generated by Django 6.0.5 on 2026-05-20 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio", "0006_alter_tfc_autor"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tfc",
            name="titulo",
            field=models.CharField(max_length=300),
        ),
    ]
