# Generated by Django 6.0.5 on 2026-05-18 12:39

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("artigos", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="like",
            name="value",
            field=models.CharField(
                choices=[("Like", "Like"), ("Unlike", "Unlike")],
                default="like",
                max_length=10,
            ),
        ),
        migrations.AlterUniqueTogether(
            name="like",
            unique_together={("autor", "artigo")},
        ),
    ]
