# Generated by Django 6.0.5 on 2026-05-18 13:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("artigos", "0002_like_value_alter_like_unique_together"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="artigo",
            name="likes",
            field=models.ManyToManyField(
                blank=True, related_name="artigos_liked", to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AlterField(
            model_name="like",
            name="artigo",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="artigos.artigo"
            ),
        ),
    ]
