# Generated by Django 6.0.5 on 2026-05-20 14:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("artigos", "0003_artigo_likes_alter_like_artigo"),
    ]

    operations = [
        migrations.AlterField(
            model_name="comentario",
            name="artigo",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="comentarios",
                to="artigos.artigo",
            ),
        ),
    ]
